name: build and push and deploy
on:
  push:
    branches:
      - env-test

permissions:
  context: read
  package: write

jobs:
  build-and-push:
    name: Build & Push
    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Print
        run: echo 'Witaj'

      - name: Uruchom Å›rodowisko docker-compose
        env:
          #DB
          POSTGRES_DB: ${{github.secrets.POSTGRES_DB}}
          POSTGRES_USER: ${{github.secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{github.secrets.POSTGRES_PASSWORD}}
        run: |
          docker-compose -f ./docker-compose/docker-compose-prge-local.yml -p local-prge up --build -d