name: build and push and deploy
on:
  push:
    branches:
      - env-test
      - env-qa
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build & Push
    runs-on:
      - self-hosted
    environment: ${{github.ref_name}}
    steps:
      - uses: actions/checkout@v3

      - name: Print
        run: echo 'Witaj'

      - name: Uruchom Å›rodowisko docker-compose

        env:
          ENV_NAME: ${{github.ref_name}}
          POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
          #DB
          POSTGRES_DB: ${{github.secrets.POSTGRES_DB}}
          POSTGRES_USER: ${{github.secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{github.secrets.POSTGRES_PASSWORD}}
        run: |
          docker-compose -f ./docker-compose/docker-compose-prge-remote.yml -p remote-prge up --build -d