name: build and push and deploy
on:
  push:
    branches:
      - env-test

permissions:
  context: read
  package: write

jobs:
  build-and-push:
    name: Build & Push
    runs-on:
      - self-hosted
